name = "medium-blogwebsite"
compatibility_date = "2024-08-11"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTc2ODVkYjUtYTNmYy00NDdjLWEwYjYtMWZlMDc5NmZmZjY2IiwidGVuYW50X2lkIjoiNDM0YWVjYmM3MWFkNzc1YmI2YjBmZWE5ZTM5MjdlZjczODZiZGIyZDhmOWY3NjgyNjY4YmEyZmVmMWU2YzQxNCIsImludGVybmFsX3NlY3JldCI6IjljYTRkMjZlLTliNzMtNDliZi1iNjk1LWFmNjM3ZTBlOWFkNSJ9.Lg9XtwFUmeYCBxz5mIXDHiA4eId6OMrX8cCMX2HxvcU"

